### GET / endpoint
GET http://localhost:3000


### Register a user, POST AUTH/REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "pranjal",
    "password": "3456hud"
}

### Login a user, POST AUTH/LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "pranjal",
    "password": "3456hud"
}

